
/* tslint:disable */
/* eslint-disable */
// this is an auto-generated file. This is not ideal but this file will normally be auto generated by amplify codegen

export const createTransformedRecord = /* GraphQL */ `
  mutation CreateTransformedRecord(
    $input: CreateTransformedRecordInput!
    $condition: ModelTransformedRecordConditionInput
  ) {
    createTransformedRecord(input: $input, condition: $condition) {
      id
      userId
      name
      email
      score
      createdAt
      updatedAt
      owner
    }
  }
`;

export const updateTransformedRecord = /* GraphQL */ `
  mutation UpdateTransformedRecord(
    $input: UpdateTransformedRecordInput!
    $condition: ModelTransformedRecordConditionInput
  ) {
    updateTransformedRecord(input: $input, condition: $condition) {
      id
      userId
      name
      email
      score
      createdAt
      updatedAt
      owner
    }
  }
`;

export const deleteTransformedRecord = /* GraphQL */ `
  mutation DeleteTransformedRecord(
    $input: DeleteTransformedRecordInput!
    $condition: ModelTransformedRecordConditionInput
  ) {
    deleteTransformedRecord(input: $input, condition: $condition) {
      id
      userId
      name
      email
      score
      createdAt
      updatedAt
      owner
    }
  }
`;
