
/* tslint:disable */
/* eslint-disable */
// this is an auto-generated file. This is not ideal but this file will normally be auto generated by amplify codegen

export const getTransformedRecord = /* GraphQL */ `
  query GetTransformedRecord($id: ID!) {
    getTransformedRecord(id: $id) {
      id
      userId
      name
      email
      score
      createdAt
      updatedAt
      owner
    }
  }
`;

export const listTransformedRecords = /* GraphQL */ `
  query ListTransformedRecords(
    $filter: ModelTransformedRecordFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listTransformedRecords(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        userId
        name
        email
        score
        createdAt
        updatedAt
        owner
      }
      nextToken
    }
  }
`;
